_target_: src.models.cnn_model.CNNModel

num_out_classes: MISSING
window_size: ${datamodule.data_hyperparameters.window_size}

num_layers: MISSING
kernel_size: MISSING
conv_stride: MISSING
initial_channel_size: MISSING
channels_factor: MISSING
dropout: MISSING
max_pool_size: MISSING
activation: ReLU
normalize_model_outputs: False
